### PR TITLE
Add '--force-node-modules' option to include node_modules as it exists.

### PR DESCRIPTION
**Pull request by sberthier**
this allow to pack a different node_module than the generated one from "npm ls --prod"

### CODE REVIEW

**Comment by heartsucker** [comment]
Hot damn. A PR with tests. Thanks for submitting.

It might take me a few days to get to this, but in the mean time I'm going to cross reference this with the other discussion in #49 in case anyone else wants to take a peek and comment on this.

**Comment by vidstige** [comment]
In what circumstances is this helpful? Just curious.

**Comment by sberthier** [comment]
With my team, we have a big directory with multiple projects that share one package.json at the root.
Each project has its own packages.json, especialy for node-deb.
We have a script to list each npm_modules used in each project recursively, and copy the minimal set of node_modules for each one.
Before the 6.0 version of node-deb, that worked very well

**Comment by heartsucker** [comment]
Closed via #63

**Pull request closed without merging**
