### PR TITLE
Add rsync-dependency to Requirements section

### PR DESCRIPTION
**Pull request by florianb**
This is needed at least for debian

### CODE REVIEW

**Comment by heartsucker** [comment]
Hey @florianb. Thanks for taking a look at this. I only switched to `rsync` because most of the packaging time is spent copying files. `rsync` offered marginal improvements, but this might be reason to remove it and see if we can still get decent performance. I'll look into that soon, but keep this PR open in the mean time.

**Comment by florianb** [comment]
Thanks @heartsucker - if there's anything i can do to support, let me know. :)

**Comment by heartsucker** [comment]
Hey @florianb. I removed the `rsync` dependency in commit b8f8797. Thanks for bringing this to my attention! I'm closing this as your issue has be resolved in another way. :)

**Comment by florianb** [comment]
Thanks @heartsucker - have a happy day! 😄

**Pull request closed without merging**
