### PR TITLE
Fixing native library dependency issue #88

### PR DESCRIPTION
**Pull request by janoskk**
Please consider merging this PR that fix issue #88

### CODE REVIEW

**Comment by heartsucker** [comment]
Thanks for the PR. Since you have more detail over in #88, some of the conversation about this PR will happen over there.

**Comment by jcvernaleo** [comment]
I've started using this PR and it seems to be working well for me.  If there are any specific tests that would help I'd be happy to do them if it would help get this one in.

**Comment by heartsucker** [comment]
Thanks for the PR. Sorry it took a few days to get merged.

**Comment by janoskk** [comment]
Great, thanks!

**Pull request merged**
