### PR TITLE
Add option "launch-startegy"

### PR DESCRIPTION
**Pull request by smennetrier**
This option offers the possibility to user
to call the entrypoint thanks to "/usr/bin/env nodejs"

BTW, it's maybe an alternative for the improvement #66

### CODE REVIEW

**Comment by heartsucker** [comment]
This definitely solves the issue, but I think this one falls a bit too much into too much configurability. I think issuing a WARN on missing executable bit and missing shebang might be sufficient.

**Comment by smennetrier** [comment]
I see, for me both are good solutions, even if I think that this option is a little more comfortable when devs (like me) use tools to generate .js file like closure compiler.

Anyway I'm OK if you prefer only display a WARN :-)

**Comment by heartsucker** [comment]
What you could do then is generate the JS files and have the entrypoint be your own shell script that's just:

```bash
#!/usr/bin/env node

/path/to/my/script.js "$@"
```

And *that* could be executable and shebang'd sufficienly. I know that takes some of the automagic away from the tool, but it might be enough. I mean, not that your PR isn't totally reasonable, but I'm just worried about the balance of the tool being general straight forward versus too configurable.

Also, there is an upper limit to how much can get packed into this before I'd just tell someone "you probably need to write your own packaging script because your use case is too complex."

**Comment by smennetrier** [comment]
Yes, no problem

**Comment by heartsucker** [comment]
Marking this as closed because it seems to be resolved.

**Pull request closed without merging**
