### PR TITLE
add OS variable, and if-else to sed command for Linux/Darwin syntax

### PR DESCRIPTION
**Pull request by pablodgonzalez**
@heartsucker Hi, How are you?
I'm making this PR with the only issue that I've found for macOS. Please check this and merge if it is useful.

Cheers!

### CODE REVIEW

**Comment by heartsucker** [comment]
Hey @pablodgonzalez, thanks for the PR. A few things.

- Can you give me some details about what version of macOS you're running?
- And the version of `sed` too?
- Is this the builtin `sed` or one you installed for `homebrew`?
- Can you modify `node-deb` to run with `set -x` post the output to a gist so I can see what exactly went wrong?

I'm only asking because I have no way of testing this myself, and I'm going to have to find a friend withe a Mac to test this.  And I think there's other instances of `sed` that we might have to fix too.

Thanks!

**Comment by heartsucker** [comment]
Also, @travis-ci seems to have errored on this because of "suspected abuse," so I had to run it manually, and it's all green on this end.

**Comment by underscorebrody** [comment]
@pablodgonzalez I'm running in to this too, so let me know if you want me to pick it up and address @heartsucker 's concerns. Thanks!

**Comment by pablodgonzalez** [comment]
@heartsucker @underscorebrody Hi guys, I so sorry, I am working over some other projects rigth now and I have no time to test this. But sooner or later I have to work on this.
Some things:
Can you give me some details about what version of macOS you're running?
**Yes, it is macOS High sierra (right now 10.13.2) I think when I've found the issue it's been 10.13)**
And the version of sed too?
```bash
$FreeBSD: src/usr.bin/sed/compile.c,v 1.28 2005/08/04 10:05:11 dds Exp $
$FreeBSD: src/usr.bin/sed/main.c,v 1.36 2005/05/10 13:40:50 glebius Exp $
$FreeBSD: src/usr.bin/sed/misc.c,v 1.10 2004/08/09 15:29:41 dds Exp $
$FreeBSD: src/usr.bin/sed/process.c,v 1.39 2005/04/09 14:31:41 stefanf Exp $
```
Is this the builtin sed or one you installed for homebrew?
**the builtin**
Can you modify node-deb to run with set -x post the output to a gist so I can see what exactly went wrong?
**When I come back to the project I'll do it**

**Comment by pablodgonzalez** [comment]
Hi @heartsucker @underscorebrody .
When I run node-deb with set -x I get this
```bash
++ escape www-xxxxxx_1.0.0-release.55_all
++ sed -e 's/[]\/$*.^|[]/\\&/g' -e 's/&/\\&/g'
+ sed -i 's/www-xxxxxx_1\.0\.0-release\.55_all//' www-xxxxxx_1.0.0-release.55_all/DEBIAN/md5sums
sed: 1: "www-xxxxxx_1.0.0-rele ...": extra characters at the end of d command
```
So, the solution still being the same, because the syntax of sed in osx is a little different

**Comment by heartsucker** [comment]
Ok cool, looks good to me.

**Comment by heartsucker** [comment]
Version `0.10.4` has been published to npm and contains this fix. :D

**Comment by pablodgonzalez** [comment]
👍🏻👍🏻👍🏻

**Pull request merged**
