### PR TITLE
Fix/node modules bug

### PR DESCRIPTION
**Pull request by vidstige**
- Fixing an issue where npm modules having their own node_module dirs caused the final deb package to contain no node_modules at all.
- Adding test case for this. I discovered this as jsonwebtoken npm module that I use triggers error.

### CODE REVIEW

**Comment by vidstige** [comment]
What's the status on this? Should I go back to 0.5.2 for now?

**Comment by heartsucker** [comment]
@vidstige It might take a bit. Between work, other projects, and life AFK, I'm fairly busy.

**Comment by vidstige** [comment]
ah, life AFK I remember that, I should start with that again ;-) 

Aright, cool, thanks for the info, I'll use 0.5.2 for now, Works like a charm

**Comment by heartsucker** [comment]
I'm going to close this in favor of the discussion in #49 since they address the same underlying issue.

**Pull request closed without merging**
